In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/MFG10YearTerminationData.csv")

In [3]:
df.shape

(49653, 18)

In [4]:
df.head()

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
0,1318,12/31/2006 0:00,1954-01-03,1989-08-28,1900-01-01,52,17,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2006,ACTIVE,HEADOFFICE
1,1318,12/31/2007 0:00,1954-01-03,1989-08-28,1900-01-01,53,18,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2007,ACTIVE,HEADOFFICE
2,1318,12/31/2008 0:00,1954-01-03,1989-08-28,1900-01-01,54,19,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2008,ACTIVE,HEADOFFICE
3,1318,12/31/2009 0:00,1954-01-03,1989-08-28,1900-01-01,55,20,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2009,ACTIVE,HEADOFFICE
4,1318,12/31/2010 0:00,1954-01-03,1989-08-28,1900-01-01,56,21,Vancouver,Executive,CEO,35,M,Male,Not Applicable,Not Applicable,2010,ACTIVE,HEADOFFICE

In [5]:
'''
EmployeeID:çalışanın benzersiz kimliği
recorddate_key:kaydın ait olduğu tarih
birthdate_key:çalışanın doğum tarihi
orighiredate_key:çalışanın işe giriş tarihi
terminationdate_key:çalışanın işten ayrılma tarihi
age:çalışanın yaşı
length_of_service:çalışanın şirkette çalışma süresi
city_name:kayıttaki şehrin adı
department_name:çalışanın çalıştığı departman
job_title:çalışanın iş unvanı
store_name:çalıştığı mağazanın adı
gender_short:cinsiyetin kısa kodu
gender_full:cinsiyetin uzun kodu
termreason_desc:ayrılma sebebi
termtype_desc:ayrılma türü
STATUS_YEAR: kaydın ait olduğu yıl
STATUS: o yılki çalışan durumu
BUSINESS_UNIT: çalışanın çalıştığı iş birimi
'''

'\nEmployeeID:çalışanın benzersiz kimliği\nrecorddate_key:kaydın ait olduğu tarih\nbirthdate_key:çalışanın doğum tarihi\norighiredate_key:çalışanın işe giriş tarihi\nterminationdate_key:çalışanın işten ayrılma tarihi\nage:çalışanın yaşı\nlength_of_service:çalışanın şirkette çalışma süresi\ncity_name:kayıttaki şehrin adı\ndepartment_name:çalışanın çalıştığı departman\njob_title:çalışanın iş unvanı\nstore_name:çalıştığı mağazanın adı\ngender_short:cinsiyetin kısa kodu\ngender_full:cinsiyetin uzun kodu\ntermreason_desc:ayrılma sebebi\ntermtype_desc:ayrılma türü\nSTATUS_YEAR: kaydın ait olduğu yıl\nSTATUS: o yılki çalışan durumu\nBUSINESS_UNIT: çalışanın çalıştığı iş birimi\n'

In [6]:
print("Benzersiz çalışan sayısı:", df['EmployeeID'].nunique())

Benzersiz çalışan sayısı: 6284

In [7]:
print("İlk yıl:", df["STATUS_YEAR"].min())
print("Son yıl:", df["STATUS_YEAR"].max())
#veri seti hangi yılları kapsıyor
#toplam 10 yıllık çalışan kayıtları var.

İlk yıl: 2006
Son yıl: 2015

In [8]:
df.dtypes

EmployeeID              int64
recorddate_key         object
birthdate_key          object
orighiredate_key       object
terminationdate_key    object
age                     int64
length_of_service       int64
city_name              object
department_name        object
job_title              object
store_name              int64
gender_short           object
gender_full            object
termreason_desc        object
termtype_desc          object
STATUS_YEAR             int64
STATUS                 object
BUSINESS_UNIT          object
dtype: object

In [9]:
df.isna().sum()
#nan hücre yok

EmployeeID             0
recorddate_key         0
birthdate_key          0
orighiredate_key       0
terminationdate_key    0
age                    0
length_of_service      0
city_name              0
department_name        0
job_title              0
store_name             0
gender_short           0
gender_full            0
termreason_desc        0
termtype_desc          0
STATUS_YEAR            0
STATUS                 0
BUSINESS_UNIT          0
dtype: int64

In [10]:
df.describe()

,EmployeeID,age,length_of_service,store_name,STATUS_YEAR
count,49653.000000,49653.000000,49653.000000,49653.000000,49653.000000
mean,4859.495740,42.077035,10.434596,27.297605,2010.612612
std,1826.571142,12.427257,6.325286,13.514134,2.845577
min,1318.000000,19.000000,0.000000,1.000000,2006.000000
25%,3360.000000,31.000000,5.000000,16.000000,2008.000000
50%,5031.000000,42.000000,10.000000,28.000000,2011.000000
75%,6335.000000,53.000000,15.000000,42.000000,2013.000000
max,8336.000000,65.000000,26.000000,46.000000,2015.000000

In [11]:
df["STATUS"].value_counts()

STATUS
ACTIVE        48168
TERMINATED     1485
Name: count, dtype: int64

In [12]:
df.loc[df["STATUS"] == "TERMINATED", "EmployeeID"].nunique()
#aynı çalışanın birden fazla ayrılma kaydı olabilir mi diye kontrol ediyoruz

1485

In [13]:
df.loc[
    df["STATUS"] == "TERMINATED",
    "termreason_desc"
].value_counts()
#çalışanların ayrılma sebeplerinin dağılımını kontrol ediyoruz
#885 emeklilik 
#385 istifa
#215 işten çıkarılma

termreason_desc
Retirement    885
Resignaton    385
Layoff        215
Name: count, dtype: int64

In [14]:
df.loc[
    df["STATUS"] == "TERMINATED",
    "termtype_desc"
].value_counts()
#kaç çalışanın gönüllü kaçının gönülsüz ayrıldığını kontrol ediyoruz

termtype_desc
Voluntary      1270
Involuntary     215
Name: count, dtype: int64

In [15]:
df.duplicated().sum()
#tekrarlayan kayıt yok - 0

np.int64(0)

In [16]:
df.duplicated(subset=["EmployeeID", "STATUS_YEAR"]).sum()

np.int64(5)

In [17]:
df.loc[
    df.duplicated(subset=["EmployeeID", "STATUS_YEAR"], keep=False)
].sort_values(["EmployeeID", "STATUS_YEAR"])
#aynı yıl içinde hem active hem de ayrılmış olduğu için aynı çalışan var

,EmployeeID,recorddate_key,birthdate_key,orighiredate_key,terminationdate_key,age,length_of_service,city_name,department_name,job_title,store_name,gender_short,gender_full,termreason_desc,termtype_desc,STATUS_YEAR,STATUS,BUSINESS_UNIT
9679,3008,12/31/2007 0:00,1942-12-31,1994-07-08,2007-12-31,65,13,Vancouver,Dairy,Dairy Person,35,F,Female,Retirement,Voluntary,2007,ACTIVE,STORES
49258,3008,12/1/2007 0:00,1942-12-31,1994-07-08,2007-12-31,65,13,Vancouver,Dairy,Dairy Person,35,F,Female,Retirement,Voluntary,2007,TERMINATED,STORES
12167,3401,12/31/2008 0:00,1943-12-31,1995-07-08,2008-12-31,65,13,Victoria,Meats,Meat Cutter,37,F,Female,Retirement,Voluntary,2008,ACTIVE,STORES
49475,3401,12/1/2008 0:00,1943-12-31,1995-07-08,2008-12-31,65,13,Victoria,Meats,Meat Cutter,37,F,Female,Retirement,Voluntary,2008,TERMINATED,STORES
41843,7007,12/31/2009 0:00,1984-11-08,2008-08-02,2009-12-31,25,1,Cranbrook,Processed Foods,Shelf Stocker,8,F,Female,Resignaton,Voluntary,2009,ACTIVE,STORES
48299,7007,12/1/2009 0:00,1984-11-08,2008-08-02,2009-12-31,25,1,Cranbrook,Processed Foods,Shelf Stocker,8,F,Female,Resignaton,Voluntary,2009,TERMINATED,STORES
41966,7023,12/31/2014 0:00,1984-12-31,2008-08-30,2014-12-31,30,6,Kelowna,Processed Foods,Shelf Stocker,16,F,Female,Resignaton,Voluntary,2014,ACTIVE,STORES
48528,7023,12/1/2014 0:00,1984-12-31,2008-08-30,2014-12-31,30,6,Kelowna,Processed Foods,Shelf Stocker,16,F,Female,Resignaton,Voluntary,2014,TERMINATED,STORES
48049,8296,12/31/2013 0:00,1994-09-02,2013-10-09,2013-12-31,19,0,Kelowna,Customer Service,Cashier,16,F,Female,Resignaton,Voluntary,2013,ACTIVE,STORES
48553,8296,12/1/2013 0:00,1994-09-02,2013-10-09,2013-12-31,19,0,Kelowna,Customer Service,Cashier,16,F,Female,Resignaton,Voluntary,2013,TERMINATED,STORES

In [ ]:
employee_left = (
    df["STATUS"].eq("TERMINATED")
    .groupby(df["EmployeeID"])
    .any()
)

employee_left.value_counts()
#1485 çalışan ayrılmış
#4799 çalışan ayrılmamış

STATUS
False    4799
True     1485
Name: count, dtype: int64